---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker-qa
  name: kafka-service-qa
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker-qa
  type: LoadBalancer
  loadBalancerIP: "35.238.235.180"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker-qa
  name: kafka-broker-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-qa
  template:
    metadata:
      labels:
        app: kafka-broker-qa
    spec:
      hostname: kafka-broker-qa
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.0.19.21:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://34.67.106.181:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker-qa
        ports:
        - containerPort: 9092
