apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service-qa
  name: zookeeper-service-qa
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30182
      targetPort: 2181
  selector:
    app: zookeeper-qa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-qa
  name: zookeeper-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-qa
  template:
    metadata:
      labels:
        app: zookeeper-qa
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper-qa
          ports:
            - containerPort: 2181
