---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-1-prod
  template:
    metadata:
      labels:
        component: kafka-1-prod
    spec:
      containers:
      - name: kafka-1-prod 
        image: wurstmeister/kafka
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-ip-service-prod:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 34.67.106.181
        tty: true
        livenessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        # command:
        #   - /bin/bash
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-ip-service-prod
spec:
  ports:
  - port: 9092
    nodePort: 30718
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-prod
    id: "0"
  type: LoadBalancer
  loadBalancerIP: "34.67.106.181"
          
