---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-prod
  labels:
    name: kafka-prod
spec:
  ports:
  - port: 9092
    nodePort: 30718
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-prod
    id: "0"
  type: LoadBalancer
  loadBalancerIP: "34.67.106.181"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-prod
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-prod
        id: "0"
  template:
    metadata:
      labels:
        app: kafka-prod
        id: "0"
    spec:
      containers:
      - name: kafka-prod
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30718"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 34.67.106.181
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-prod:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE 
          value: "true"
        - name: KAFKA_ADVERTISED_LISTENERS 
          value: PLAINTEXT://34.67.106.181:30718
          
