apiVersion: v1
kind: Service
metadata:
  name: kafka-service-prod
  labels:
    name: kafka-prod
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-prod
    id: "0"
  type: LoadBalancer
  loadBalancerIP: "34.67.106.181"
  
