apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service-prod
  name: zookeeper-service-prod
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-prod
  name: zookeeper-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-prod
  template:
    metadata:
      labels:
        app: zookeeper-prod
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper-prod
          ports:
            - containerPort: 2181
