---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper-prod
  template:
    metadata:
      labels:
        component: zookeeper-prod
    spec:
      containers:
      - name: zookeeper-prod
        image: wurstmeister/zookeeper        
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
          - containerPort: 2181
        tty: true
        livenessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /opt/check.sh
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ip-service-prod
spec:
  type: ClusterIP 
  selector:
    component: zookeeper-prod
  ports:
  - name: zookeeper-prod
    port: 2181
    targetPort: 2181
