---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper-prod
  template:
    metadata:
      labels:
        app: zookeeper-prod
    spec:
      containers:
      - name: zookeeper-prod
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-prod
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-prod
  labels:
    app: zookeeper-prod
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-prod
